name: chux
description: "Lightweight CRUD-style state management for Flutter. Manage state as simply as creating a variable, with full reactivity and zero boilerplate."
version: 1.0.0
repository: 
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
